# Documentation available at https://expeditor.chef.io/docs/getting-started/
---
# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel: inspec-notify

# This publish is triggered by the `built_in:publish_rubygems` artifact_action.
rubygems:
  - train-aws

github:
  # This deletes the GitHub PR branch after successfully merged into the release branch
  delete_branch_on_merge: true
  # The tag format to use (e.g. v1.0.0)
  version_tag_format: "v{{version}}"
  # allow bumping the minor release via label
  minor_bump_labels:
    - "CI/Bump Minor Version"
  major_bump_labels:
    - "CI/Bump Major Version"

changelog:
  rollup_header: Changes not yet released to rubygems.org

subscriptions:
# These actions are taken, in the order they are specified, anytime a Pull Request is merged.
  - workload: pull_request_merged:{{github_repo}}:{{release_branch}}:*
    actions:
      - built_in:bump_version:
         ignore_labels:
          - "CI/Skip Version Bump"
          - "CI/Skip All"
      - bash:.expeditor/update_version.sh:
         only_if:
          - built_in:bump_version
      - built_in:update_changelog:
         ignore_labels:
          - "CI/Skip Changelog"
          - "CI/Skip All"
      - built_in:build_gem:
         only_if:
          - built_in:bump_version

  - workload: project_promoted:{{agent_id}}:*
    actions:
     - built_in:rollover_changelog
     - built_in:publish_rubygems

pipelines:
  - verify:
      description: Pull Request validation tests
      public: true
